default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
        language_version: python3.12
      - id: check-yaml
        language_version: python3.12
      - id: end-of-file-fixer
        language_version: python3.12
      - id: trailing-whitespace
        language_version: python3.12
