model_name: HuggingFaceTB/SmolLM3-3B
run_name: base_llm_demo
torch_dtype: bfloat16
device: null
prompt: |
  MegaContext virtualizes long-term memory. Explain the core idea in two sentences.
max_new_tokens: 64
do_sample: false
temperature: 0.7
wandb_project: megacontext-poc
