model:
  hidden_size: 768
  block_size: 32
  num_heads: 12
  mlp_ratio: 4.0
  rope_base: 10000.0
training:
  batch_size: 2
  lr: 0.0005
  max_steps: 400
  device: cuda
  seed: 0
  run_name: gistnet-example
