model:
  hidden_size: 2
  block_size: 4
  num_heads: 2
  mlp_ratio: 2.0
  rope_base: 10000.0
training:
  batch_size: 8
  lr: 0.001
  max_steps: 200
  device: cpu
  seed: 0
  run_name: gistnet-example
